# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo DEV First Job

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo QA First Job

- stage: Proddeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo PROD First Job

